### ISSUE TITLE
Issue Running with Shinyjs

### ISSUE THREAD

**Issue by lvieira135** [matdoering/openPrimeR-User#3]
Dear,

When trying to run your package I have encountered the following error when opening the browser page (through startApp() command): 

shinyjs: extendShinyjs: `functions` argument must not contain any of the following function names: reset

Have you ever encountered this error or can you tell me what might be causing it?

Thanks in advance!

Lucas Vieira

**Comment by mattheiter** [comment]
Hey Lucas,
`shinyjs` is no longer maintained, so `openPrimeRui` doesn't work with newer versions of R anymore. If you want to use the UI, you can still use the [docker image](https://hub.docker.com/r/mdoering88/openprimer/). Otherwise, you'll have to switch to the [openPrimeR R package](https://www.bioconductor.org/packages/release/bioc/html/openPrimeR.html).
